export const state = () => ({
  roles: {
    junior: {
      communication: [
        'Proactive, Continuous Feedback Loop',
        'Value supervision by mentor',
        'Ask Questions',
        'Communicate status updates',
        'Understand greater technical concepts',
      ],
      execution: [
        'Structured and efficient',
        'Visible and planned with work broken down into tasks',
        'Active project participation',
        'Demand learning sessions with mentor',
      ],
      implementation: [
        'Follow best practices',
        'Develop knowledge of a single component of our architecture',
        'Write tests',
        'Develop individual areas within a solution',
        'Solve local problems',
      ],
      teamwork: [
        'Open dialogue',
        'Share learnings',
        'Value diverse personalities',
        'Accept feedback as a way to improve and grow',
      ],
      innovation: ['Challenge and improve tools, workflows and processes'],
    },
    professional: {
      communication: [
        'Proactive, Continuous Feedback Loop',
        "Understand stakeholder's point of view",
        'Communicate assumptions and get clarification',
        'Fight for Simplicity',
        'Solicit feedback from others',
        'Keep cool under pressure',
        'Teach greater technical concepts',
      ],
      execution: [
        'Work self-reliantly',
        'Understand how work fits in to the larger project',
        'Active project participation',
        'Structured and efficient',
        'Visible and planned with work broken down into tasks',
        'Facilitate decision making',
        'Take responsibility for the team',
      ],
      implementation: [
        'Follow best practices',
        'Take responsibility for the solution',
        'Know and apply software design rules',
        'Write meaningful tests',
        'Develop solutions that meet the requirements',
        'Demand and actively participate design sessions',
        'Responsibility for large parts of a codebase of an application and connected systems',
      ],
      teamwork: [
        'Open dialogue',
        'Meet and follow up on set appointments',
        'Being transparent towards internal and external contacts',
        'Assume responisibility for lesser experienced employees',
        'Share knowledge and learnings',
        'Live team values',
      ],
      innovation: ['Challenge and improve tools, workflows and processes'],
    },
    senior: {
      communication: [
        'Communicate technical decisions through design docs, tech talks and wiki',
        'Lead know-how sessions',
        'Assertiveness',
        'Decision making ability',
        'Conflict resolution skills',
        'Identify problems/risks of own work and the work of others',
        'Teach others about greater concepts',
        'Proactive, Continuous Feedback Loop',
        "Understand stakeholder's point of view. Fight for Simplicity",
      ],
      execution: [
        'Active contribution during demo sessions',
        'Take responsibility for the software solution',
        'User-centric software design',
        'Look at test cases and advice QA on adjacent code/regression impact',
        'Structured and efficient',
        'Techincal Project Management',
        'Visible and planned with work broken down into tasks',
        'Facilitate decision making',
        'Take responsibility for the team',
      ],
      implementation: [
        'Design patterns and anti patterns profiling',
        'Actively improve software quality',
        'Introduce improvements to the development process',
        'Take end-to-end responsibility',
        'Contribute to common code',
        'Ability to create a greater concept',
        'Develop and introduce best practices',
        'Take responsibility for the solution',
      ],
      teamwork: [
        'Ability to work well with product, design, analytics, ... as necessary',
        'Mentor less experienced engineers via pair programming, design and code reviews',
        'Cross-functional team player who enables other teams to reach their goals',
        'Open dialogue',
        'Help shape common guidelines',
        'Supervise and guide others',
        'Share knowledge',
        'Value diverse personalities',
        'Drive team values and coach others',
      ],
      innovation: ['Challenge and improve tools, workflows and processes'],
    },
  },
})
